server:
  port: 9192

spring:
  h2:
    console:
      enabled: true
  application:
    name: PAYMENT-SERVICE

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9196/eureka
  instance:
    hostname: localhost