spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      mvc:
        routes:
          - id: order-service
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/order/**
          - id: payment-service
            uri: lb://PAYMENT-SERVICE
            predicates:
              - Path=/payment/**



server:
  port: 9097

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9196/eureka
  instance:
    hostname: localhost